k = 0.7;

figure(1)
hold("on");
box("on");
plot(100:50:100+(nTopo-1)*50, [mean(delayEndToEnd_DBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-.", ...
     "Marker","square", ...
     "MarkerSize", 8, ...
     "Color", "k");
plot(100:50:100+(nTopo-1)*50, [mean(delayEndToEnd_EEDBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "--", ...
     "Marker","*", ...
     "MarkerSize", 8, ...
     "Color", "b");
plot(100:50:100+(nTopo-1)*50, [mean(delayEndToEnd_REPBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", ":", ...
     "Marker","^", ...
     "MarkerSize", 8, ...
     "Color", "#22B14C");
plot(100:50:100+(nTopo-1)*50, [mean(delayEndToEnd_CUSTOM, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-", ...
     "Marker","o", ...
     "MarkerSize", 8, ...
     "Color", "r");
for i = 1 : nTopo
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(delayEndToEnd_DBR(:, i)), min(delayEndToEnd_DBR(:, i))] + k * mean(delayEndToEnd_DBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "k");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(delayEndToEnd_EEDBR(:, i)), min(delayEndToEnd_EEDBR(:, i))] + k * mean(delayEndToEnd_EEDBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "b");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(delayEndToEnd_REPBR(:, i)), min(delayEndToEnd_REPBR(:, i))] + k * mean(delayEndToEnd_REPBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "#22B14C");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(delayEndToEnd_CUSTOM(:, i)), min(delayEndToEnd_CUSTOM(:, i))] + k * mean(delayEndToEnd_CUSTOM(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "r");
end
xlabel("number of nodes")
ylabel("end-to-end delay (s)")
legend("DBR", "EEDBR", "REPBR", "CUSTOM", "Location", "southeast");
handle = gca;
handle.LineWidth = 1;
handle.XTick = [100 : 50 : 100 + (nTopo - 1) * 50];
xlim([90, 100 + (nTopo - 1) * 50 + 10])



figure(2)
hold("on");
box("on");
plot(100:50:100+(nTopo-1)*50, [mean(deliveryRatio_DBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-.", ...
     "Marker","square", ...
     "MarkerSize", 8, ...
     "Color", "k");
plot(100:50:100+(nTopo-1)*50, [mean(deliveryRatio_EEDBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "--", ...
     "Marker","*", ...
     "MarkerSize", 8, ...
     "Color", "b");
plot(100:50:100+(nTopo-1)*50, [mean(deliveryRatio_REPBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", ":", ...
     "Marker","^", ...
     "MarkerSize", 8, ...
     "Color", "#22B14C");
plot(100:50:100+(nTopo-1)*50, [mean(deliveryRatio_CUSTOM, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-", ...
     "Marker","o", ...
     "MarkerSize", 8, ...
     "Color", "r");
for i = 1 : nTopo
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(deliveryRatio_DBR(:, i)), min(deliveryRatio_DBR(:, i))] + k * mean(deliveryRatio_DBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "k");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(deliveryRatio_EEDBR(:, i)), min(deliveryRatio_EEDBR(:, i))] + k * mean(deliveryRatio_EEDBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "b");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(deliveryRatio_REPBR(:, i)), min(deliveryRatio_REPBR(:, i))] + k * mean(deliveryRatio_REPBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "#22B14C");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(deliveryRatio_CUSTOM(:, i)), min(deliveryRatio_CUSTOM(:, i))] + k * mean(deliveryRatio_CUSTOM(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "r");
end
xlabel("number of nodes")
ylabel("packet delivery ratio")
legend("DBR", "EEDBR", "REPBR", "CUSTOM", "Location", "southwest");
handle = gca;
handle.LineWidth = 1;
handle.XTick = [100 : 50 : 100 + (nTopo - 1) * 50];
xlim([90, 100 + (nTopo - 1) * 50 + 10])

%% 
figure(3)
hold("on");
box("on");
plot(100:50:100+(nTopo-1)*50, [mean(energyConsumption_DBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-.", ...
     "Marker","square", ...
     "MarkerSize", 8, ...
     "Color", "k");
plot(100:50:100+(nTopo-1)*50, [mean(energyConsumption_EEDBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "--", ...
     "Marker","*", ...
     "MarkerSize", 8, ...
     "Color", "b");
plot(100:50:100+(nTopo-1)*50, [mean(energyConsumption_REPBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", ":", ...
     "Marker","^", ...
     "MarkerSize", 8, ...
     "Color", "#22B14C");
plot(100:50:100+(nTopo-1)*50, [mean(energyConsumption_CUSTOM, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-", ...
     "Marker","o", ...
     "MarkerSize", 8, ...
     "Color", "r");
for i = 1 : nTopo
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(energyConsumption_DBR(:, i)), min(energyConsumption_DBR(:, i))] + k * mean(energyConsumption_DBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "k");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(energyConsumption_EEDBR(:, i)), min(energyConsumption_EEDBR(:, i))] + k * mean(energyConsumption_EEDBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "b");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(energyConsumption_REPBR(:, i)), min(energyConsumption_REPBR(:, i))] + k * mean(energyConsumption_REPBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "#22B14C");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(energyConsumption_CUSTOM(:, i)), min(energyConsumption_CUSTOM(:, i))] + k * mean(energyConsumption_CUSTOM(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "r");
end
xlabel("number of nodes")
ylabel("energy consumption (J)")
legend("DBR", "EEDBR", "REPBR", "CUSTOM", "Location", "northwest");
handle = gca;
handle.LineWidth = 1;
handle.XTick = [100 : 50 : 100 + (nTopo - 1) * 50];
xlim([90, 100 + (nTopo - 1) * 50 + 10])

%% 
figure(4)
hold("on");
box("on");
plot(100:50:100+(nTopo-1)*50, [mean(networkLifetime_DBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-.", ...
     "Marker","square", ...
     "MarkerSize", 8, ...
     "Color", "k");
plot(100:50:100+(nTopo-1)*50, [mean(networkLifetime_EEDBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "--", ...
     "Marker","*", ...
     "MarkerSize", 8, ...
     "Color", "b");
plot(100:50:100+(nTopo-1)*50, [mean(networkLifetime_REPBR, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", ":", ...
     "Marker","^", ...
     "MarkerSize", 8, ...
     "Color", "#22B14C");
plot(100:50:100+(nTopo-1)*50, [mean(networkLifetime_CUSTOM, 'omitnan')]', ...
     "LineWidth", 1, ...
     "LineStyle", "-", ...
     "Marker","o", ...
     "MarkerSize", 8, ...
     "Color", "r");
for i = 1 : nTopo
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(networkLifetime_DBR(:, i)), min(networkLifetime_DBR(:, i))] + k * mean(networkLifetime_DBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "k");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(networkLifetime_EEDBR(:, i)), min(networkLifetime_EEDBR(:, i))] + k * mean(networkLifetime_EEDBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "b");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(networkLifetime_REPBR(:, i)), min(networkLifetime_REPBR(:, i))] + k * mean(networkLifetime_REPBR(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "#22B14C");
    plot([100 + 50 * (i - 1), 100 + 50 * (i - 1)], (1 - k) * [max(networkLifetime_CUSTOM(:, i)), min(networkLifetime_CUSTOM(:, i))] + k * mean(networkLifetime_CUSTOM(:, i), 'omitnan'), ...
         "LineWidth", 1, ...
         "Marker",".", ...
         "MarkerSize", 8, ...
         "Color", "r");
end
xlabel("number of nodes")
ylabel("network lifetime (s)")
legend("DBR", "EEDBR", "REPBR", "CUSTOM", "Location", "northeast");
handle = gca;
handle.LineWidth = 1;
handle.XTick = [100 : 50 : 100 + (nTopo - 1) * 50];
xlim([90, 100 + (nTopo - 1) * 50 + 10])